# Exercícios Pandas

#### 1)  crie uma série do pandas a partir de uma lista com os dados abaixo:

Em um estudo sobre alteração na tempreatura global, A NASA disponibiliza dados de diferenças de temperatura média da superfície terrestre relativos às médias de temperatura entre 1951 e 1980. Os dados originais podem ser vistos no site da NASA/GISS, e estão dispostos a cada década na tabela abaixo.

|ano|anomalia térmica|
|:-:|:----:|
| 1900 | -0.08 |
| 1920 | -0.27 |
| 1940 | 0.12 |
| 1960 | -0.03 |
| 1980 | 0.26 |
| 2000 | 0.40 |
| 2020 | 1.02 |

Crie uma séries do Pandas a partir de uma lista com esses dados.

In [116]:
import pandas as pd
import numpy as np
import math

s = pd.Series([-0.08,-0.27,0.12,-0.03,0-26,0.40,1.02], index = [1900,1920,1940,1960,1980,2000,2020], name = 'Anomalia Térmica')
s

1900    -0.08
1920    -0.27
1940     0.12
1960    -0.03
1980   -26.00
2000     0.40
2020     1.02
Name: Anomalia Térmica, dtype: float64

#### 2) Coloque os anos nos índices conforme a tabela.

In [96]:
# seu código aqui
s

1900    -0.08
1920    -0.27
1940     0.12
1960    -0.03
1980   -26.00
2000     0.40
2020     1.02
Name: Anomalia Térmica, dtype: float64

#### 3) A partir do dicionário abaixo, crie uma séries do Pandas:

In [105]:
dic_temperaturas = {1900: -.08, 1920: -.27, 1940: .12, 1960: -.03, 1980: .26, 2000: .40, 2020: 1.02}

# seu código aqui
dct = pd.Series(dic_temperaturas,name='Anomalia Térmica')
dct

1900   -0.08
1920   -0.27
1940    0.12
1960   -0.03
1980    0.26
2000    0.40
2020    1.02
Name: Anomalia Térmica, dtype: float64

#### 4) Transforme o ndarray abaixo em um dataframe.
O numpy é capaz de gerar arrays n-dimensionais com números pseudo-aleatórios de acordo com uma variedade de distribuições, como no exemplo abaixo. Transforme esse nd-array em um DataFrame.

In [106]:
arr = np.random.normal(100, 10, (20,3))

# seu código aqui

dt = pd.DataFrame(arr)
dt

             0           1           2
0    91.898462  104.543699  106.944082
1   103.572942  103.114141  109.697272
2    90.474211   98.648827  111.862865
3   101.507835  102.688824   90.568628
4    92.149295   97.545360   92.454656
5   103.530889   99.041516   93.380812
6   105.340457   98.354511   81.171812
7    97.034828  122.958943  102.446859
8    86.734762   83.475113  103.650098
9   108.223323   99.011748  103.142452
10  101.456755   91.896270   89.536281
11   99.523593  105.102465  110.699036
12  107.443765   91.498132  108.918905
13  110.265562   94.499941   84.623001
14  105.286846   88.027593   89.185692
15   79.047973  111.608646  101.243494
16  115.921714  110.431281   98.910154
17  101.787243  108.143673   93.416346
18   89.532838  101.704259  114.842002
19  111.038059   93.421558   87.781028

#### 5) Nomeie os índices das linhas com inteiros de 1 a 20, e as colunas com os nomes "x1", "x2", e "x3" respectivamente.

In [112]:
#seu código aqui

dt.columns = ['x1', 'x2', 'x3']
dt.index = range(1,21)
dt

            x1          x2          x3
1    91.898462  104.543699  106.944082
2   103.572942  103.114141  109.697272
3    90.474211   98.648827  111.862865
4   101.507835  102.688824   90.568628
5    92.149295   97.545360   92.454656
6   103.530889   99.041516   93.380812
7   105.340457   98.354511   81.171812
8    97.034828  122.958943  102.446859
9    86.734762   83.475113  103.650098
10  108.223323   99.011748  103.142452
11  101.456755   91.896270   89.536281
12   99.523593  105.102465  110.699036
13  107.443765   91.498132  108.918905
14  110.265562   94.499941   84.623001
15  105.286846   88.027593   89.185692
16   79.047973  111.608646  101.243494
17  115.921714  110.431281   98.910154
18  101.787243  108.143673   93.416346
19   89.532838  101.704259  114.842002
20  111.038059   93.421558   87.781028

#### 6) No DataFrame do exercício 5, crie uma nova coluna como sendo a média das três colunas, e dê a ela o nome de "media" (não recomendo colocar acentos em nomes de variáveis).

In [113]:
# seu código aqui

dt['Media'] = dt.mean(axis=1)
dt

            x1          x2          x3       Media
1    91.898462  104.543699  106.944082  101.128748
2   103.572942  103.114141  109.697272  105.461452
3    90.474211   98.648827  111.862865  100.328635
4   101.507835  102.688824   90.568628   98.255095
5    92.149295   97.545360   92.454656   94.049770
6   103.530889   99.041516   93.380812   98.651072
7   105.340457   98.354511   81.171812   94.955593
8    97.034828  122.958943  102.446859  107.480210
9    86.734762   83.475113  103.650098   91.286658
10  108.223323   99.011748  103.142452  103.459174
11  101.456755   91.896270   89.536281   94.296435
12   99.523593  105.102465  110.699036  105.108365
13  107.443765   91.498132  108.918905  102.620267
14  110.265562   94.499941   84.623001   96.462835
15  105.286846   88.027593   89.185692   94.166710
16   79.047973  111.608646  101.243494   97.300038
17  115.921714  110.431281   98.910154  108.421049
18  101.787243  108.143673   93.416346  101.115754
19   89.532838  101.704259  114.842002  102.026366
20  111.038059   93.421558   87.781028   97.413548

#### 7) No DataFrame do exercício 6, crie uma nova coluna chamada "log_med", contendo o logaritmo natural da média calculada no exercício 6 <br>

In [115]:
# seu código aqui

dt['Log_Media'] = np.log(dt["Media"])
dt

            x1          x2          x3       Media  Log_Media
1    91.898462  104.543699  106.944082  101.128748   4.616394
2   103.572942  103.114141  109.697272  105.461452   4.658345
3    90.474211   98.648827  111.862865  100.328635   4.608451
4   101.507835  102.688824   90.568628   98.255095   4.587567
5    92.149295   97.545360   92.454656   94.049770   4.543824
6   103.530889   99.041516   93.380812   98.651072   4.591589
7   105.340457   98.354511   81.171812   94.955593   4.553409
8    97.034828  122.958943  102.446859  107.480210   4.677307
9    86.734762   83.475113  103.650098   91.286658   4.514005
10  108.223323   99.011748  103.142452  103.459174   4.639177
11  101.456755   91.896270   89.536281   94.296435   4.546443
12   99.523593  105.102465  110.699036  105.108365   4.654992
13  107.443765   91.498132  108.918905  102.620267   4.631035
14  110.265562   94.499941   84.623001   96.462835   4.569158
15  105.286846   88.027593   89.185692   94.166710   4.545067
16   79.047973  111.608646  101.243494   97.300038   4.577799
17  115.921714  110.431281   98.910154  108.421049   4.686022
18  101.787243  108.143673   93.416346  101.115754   4.616266
19   89.532838  101.704259  114.842002  102.026366   4.625231
20  111.038059   93.421558   87.781028   97.413548   4.578965

#### 8) Análise de Vendas de Jogos Eletrônicos com Pandas

1. Baixe o dataset **"Venda de jogos"** (Video Game Sales), que contém dados sobre jogos com mais de 100.000 cópias vendidas.

- Baixe a base: [Clique aqui para baixar o arquivo](https://drive.google.com/file/d/1LTQSnw4ft90OCA7k2OwPw71MGY52FrSI/view?usp=sharing)

A fonte original é o site [vgchartz.com](https://www.vgchartz.com).

2. Carregue os dados usando a biblioteca `pandas`.
3. Responda às perguntas abaixo com base na sua análise.

#### Dicionário de Dados - Venda de Jogos

Este dicionário descreve cada uma das colunas presentes no dataset de vendas de jogos eletrônicos.

| Coluna         | Tipo de Dado     | Descrição                                                                 |
|----------------|------------------|---------------------------------------------------------------------------|
| `Rank`         | Inteiro          | Posição no ranking geral de vendas globais.                              |
| `Name`         | Texto (string)   | Nome do jogo.                                                             |
| `Platform`     | Texto (string)   | Plataforma em que o jogo foi lançado (ex: PS4, PC, Xbox One, etc.).      |
| `Year`         | Numérico (float) | Ano de lançamento do jogo.                                               |
| `Genre`        | Texto (string)   | Gênero do jogo (ex: Action, Sports, RPG, etc.).                          |
| `Publisher`    | Texto (string)   | Empresa responsável pela publicação do jogo.                             |
| `NA_Sales`     | Numérico (float) | Vendas na América do Norte (em milhões de unidades).                     |
| `EU_Sales`     | Numérico (float) | Vendas na Europa (em milhões de unidades).                               |
| `JP_Sales`     | Numérico (float) | Vendas no Japão (em milhões de unidades).                                |
| `Other_Sales`  | Numérico (float) | Vendas no restante do mundo (exceto NA, EU e JP), em milhões de unidades.|
| `Global_Sales` | Numérico (float) | Total de vendas globais (em milhões de unidades).                        |


---

## Perguntas

1. **Qual foi o gênero de jogo com o maior volume de vendas globais (`Global_Sales`)?**  
   *Dica:* Use `groupby` com a coluna `Genre` e some as vendas globais.

2. **Quais são as 5 plataformas com maior média de vendas na América do Norte (`NA_Sales`)?**  
   *Dica:* Use `groupby` na coluna `Platform` e calcule a média de `NA_Sales`.

3. **Qual publisher lançou o maior número de jogos entre os anos de 2000 e 2010?**  
   *Dica:* Filtre as linhas com `Year` entre 2000 e 2010 e conte os jogos por `Publisher`.

4. **Existe alguma relação aparente entre as vendas no Japão (`JP_Sales`) e o gênero do jogo?**  
   *Dica:* Compare as médias ou medianas de `JP_Sales` por `Genre` e descreva o que observou.

---

In [157]:
from google.colab import drive
drive.mount('/content/drive')

# Caminho do diretório escolhido
path = "/content/drive/MyDrive/DataScience"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [158]:

# Leitura do arquivo
df = pd.read_csv(path + '/vgsales.csv', sep=',')

# Mostrando as 10 primeiras linhas
df.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

In [238]:
genero = pd.crosstab(df.Genre, df.Global_Sales.max())
genero.head(1)

col_0   82.74
Genre
Action   3316

In [226]:
ex2 = df.groupby('Platform')['NA_Sales'].mean().sort_values(ascending=False)
ex2.head(5)

Platform
NES     1.285102
GB      1.166531
GEN     0.713704
2600    0.681203
X360    0.475138
Name: NA_Sales, dtype: float64

In [267]:
ex3 = df[(df.Year >= 2000) & (df.Year <= 2010)].value_counts('Publisher')
ex3.head(1)

Publisher
Electronic Arts    979
Name: count, dtype: int64